"""Fix IssueDetail model

Revision ID: 4c0b2dc21684
Revises: 
Create Date: 2025-03-13 15:34:29.084036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c0b2dc21684'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.String(), nullable=True),
    sa.Column('issue_name', sa.String(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('response_period', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('response_team', sa.String(), nullable=True),
    sa.Column('government_officials', sa.String(), nullable=True),
    sa.Column('business_impact', sa.String(), nullable=True),
    sa.Column('kpi', sa.String(), nullable=True),
    sa.Column('issue_end_date', sa.Date(), nullable=True),
    sa.Column('stakeholders', sa.String(), nullable=True),
    sa.Column('result_summary', sa.String(), nullable=True),
    sa.Column('completion_status', sa.String(), nullable=True),
    sa.Column('other_remarks', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issues_id'), 'issues', ['id'], unique=False)
    op.create_index(op.f('ix_issues_issue_name'), 'issues', ['issue_name'], unique=False)
    op.create_index(op.f('ix_issues_issue_number'), 'issues', ['issue_number'], unique=True)
    op.create_table('issue_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_issue_details_id'), 'issue_details', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_issue_details_id'), table_name='issue_details')
    op.drop_table('issue_details')
    op.drop_index(op.f('ix_issues_issue_number'), table_name='issues')
    op.drop_index(op.f('ix_issues_issue_name'), table_name='issues')
    op.drop_index(op.f('ix_issues_id'), table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
