"""Add file_path to IssueDetail

Revision ID: 4f8b090c9d13
Revises: 4c0b2dc21684
Create Date: 2025-03-13 16:18:06.525574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f8b090c9d13'
down_revision: Union[str, None] = '4c0b2dc21684'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issue_details', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issue_details', 'file_path')
    # ### end Alembic commands ###
