"""create law_update table

Revision ID: 5f1b5d56449e
Revises: 9a5317648a15
Create Date: 2025-03-21 15:20:10.079702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f1b5d56449e'
down_revision: Union[str, None] = '9a5317648a15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('law_update',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('law_name', sa.String(), nullable=False),
    sa.Column('proclamation_date', sa.Date(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_law_update_id'), 'law_update', ['id'], unique=False)
    op.create_index(op.f('ix_review_proposals_id'), 'review_proposals', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_proposals_id'), table_name='review_proposals')
    op.drop_index(op.f('ix_law_update_id'), table_name='law_update')
    op.drop_table('law_update')
    # ### end Alembic commands ###
